# Generated by Django 2.2.6 on 2019-10-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0002_auto_20191010_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to=settings.AUTH_USER_MODEL),
        ),
    ]
