# Generated by Django 2.2.6 on 2019-10-11 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journal_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to=settings.AUTH_USER_MODEL),
        ),
    ]
